// LOGIN
export const FETCH_LOGIN = "FETCH_LOGIN"
export const INICIO_SESION_OK = "INICIO_SESION_OK";
export const INICIO_SESION_FAILED = "INICIO_SESION_FAILED";
export const CERRAR_SESION = "CERRAR_SESION";