// LOGIN
export const FETCH_LOGIN = "FETCH_LOGIN"
export const INICIO_SESION_OK = "INICIO_SESION_OK";
export const INICIO_SESION_FAILED = "INICIO_SESION_FAILED";
export const CERRAR_SESION = "CERRAR_SESION";

// PERSONAS
export const FETCH_PERSONAS = "FETCH_PERSONAS"
export const FETCH_PERSONAS_OK = "FETCH_PERSONAS_OK"
export const FETCH_PERSONAS_FAILED = "FETCH_PERSONAS_FAILED"

// MATERIAS
export const FETCH_MATERIAS = "FETCH_MATERIAS"
export const FETCH_MATERIAS_OK = "FETCH_MATERIAS_OK"
export const FETCH_MATERIAS_FAILED = "FETCH_MATERIAS_FAILED"